{
 "title": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ECS: Tasks stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (container_name) (rate({job=\"ecs-firelens\"}[1m])) # traffic per task"
    },
    {
     "expr": "sum by (container_name) (rate({job=\"ecs-firelens\"} |~ \" 5[0-9][0-9] \" [1m]))  # 5xx per task"
    }
   ]
  },
  {
   "title": "Digital Ocean: Error codes pie chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (class) (\n  count_over_time(\n    {job=\"flog\"}\n    | pattern `<_> - <_> [<_>] \"<_> <_> <_>\" <status> <_> \"<_>\" \"<_>\"`\n    | status =~ \"[2-5][0-9][0-9]\"\n    | label_format class=`{{ printf \"%.1s\" .status }}xx`\n    [$__range]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Digital Ocean: Number of 500 errors over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"flog\"} |= \" 500 \" or \" 502 \" or \" 503 \" [5m]))"
    }
   ]
  },
  {
   "title": "Digital Ocean: Increment value",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time({job=\"loggen\"} | pattern `<_> level=<_> msg=<_> host=<_> req=<req>` | unwrap req [2s])"
    }
   ]
  }
 ]
}